# Generated by Django 4.2.7 on 2023-12-19 09:55

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object3dmodel',
            name='texture',
            field=models.FileField(blank=True, null=True, upload_to=home.models.obj_upload_path),
        ),
    ]
